[package]
name = "opengl-scratch"
version = "0.1.0"
authors = ["AJ Morris <ajm896@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
